name: Build
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SonarQube Scanner Action
      uses: philips-software/sonar-scanner-action@v1.3.0
      with:
            projectName: test2
            projectKey: test2
    - name: Check Out Source Code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: set-up 
      uses: sonarsource/sonarqube-scan-action@master
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
